# Generated by Django 4.2.3 on 2024-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Operator', models.CharField(max_length=100)),
                ('Supervisor', models.CharField(max_length=100)),
                ('Operation', models.CharField(max_length=200)),
                ('Rework', models.BooleanField(default=False)),
                ('Scrap', models.BooleanField(default=False)),
            ],
        ),
    ]
