# Generated by Django 4.2.3 on 2024-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productform',
            name='Rework',
        ),
        migrations.RemoveField(
            model_name='productform',
            name='Scrap',
        ),
        migrations.CreateModel(
            name='ShellNumberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_no', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('relults', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('ProductForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductForm', to='form_app.productform')),
            ],
        ),
    ]
