# Generated by Django 5.0.6 on 2024-05-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_remove_productform_rework_remove_productform_scrap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shellnumberdetail',
            name='ProductForm',
        ),
        migrations.CreateModel(
            name='ShellInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_no', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('ProductionData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionData', to='form_app.productiondata')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductForm',
        ),
        migrations.DeleteModel(
            name='ShellNumberDetail',
        ),
    ]
