# Generated by Django 5.0.6 on 2024-05-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_alter_shellinspection_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shellinspection',
            name='batch',
        ),
    ]
