# Generated by Django 5.0.6 on 2024-06-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_remove_shellinspection_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shellinspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shellinspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='CriticalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('ShellInspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShellInspection', to='form_app.shellinspection')),
            ],
        ),
    ]
